from .heisenberg import get_heisenberg_equation_message
from .ampere import get_magnetic_field_message
from .boyle import get_boyle_mariotte_message
from .ohm_law import get_amperage_message
from .gravitational_force import get_gravitational_force_message