from .arc_length import get_arc_length_message
from .distance import get_distance_message
from .rectangle_square import get_rectangle_square_message
from .circle_square import get_circle_square_message